const colors = {
  base: {
    light: '#fff',
    dark: '#000',
    default: '#333',
  },
  text: {
    default: '#212121',
    error: '#ff0000',
  },
  form: {
    title: '#000',
    divider: 'rgba(151,151,151,0.3)',
    background: '#f9f9f9',
  },
  input: {
    background: '#fff',
    backgroundReadOnly: '#f3f4f4',
    border: '#ccc',
    borderHover: '#b7b7b7',
    borderFocus: '#0a84ae',
    borderError: '#ff0000',
    icon: '#a2a2a2',
    text: '#333',
    placeholder: '#b2b2b2',
    placeholderDisabled: '#c1c1c1',
    placeholderReadOnly: '#333',
    label: '#333',
    labelDisabled: '#c6c6c6',
  },
  link: {
    default: '#0a84ae',
    defaultHover: '#053b4e',
    defaultFocus: '#053b4e',
    sidebar: '#333',
    sidebarHover: '#FF3E00',
    sidebarFocus: '#FF3E00',
  },
  tooltip: {
    background: '#1A1A1A',
    text: '#FFF',
  },
  button: {
    default: {
      background: '#F1F1F1',
      backgroundHover: '#E9E8E8',
      backgroundFocus: '#E9E8E8',
      backgroundActive: '#DADADA',
      text: '#333',
      icon: 'default',
      border: '#F1F1F1',
      borderHover: '#E9E8E8',
      borderFocus: '#E9E8E8',
      borderActive: '#DADADA',
    },
    primary: {
      background: '#44C7F4',
      backgroundHover: '#13B7ED',
      backgroundFocus: '#13B7ED',
      backgroundActive: '#11A7D9',
      text: '#FAFAFA',
      icon: 'white',
      border: '#44C7F4',
      borderHover: '#13B7ED',
      borderFocus: '#13B7ED',
      borderActive: '#11A7D9',
    },
    secondary: {
      background: 'transparent',
      backgroundHover: 'rgba(0,0,0,0.05)',
      backgroundFocus: 'rgba(0,0,0,0.05)',
      backgroundActive: '#DADADA',
      text: '#333',
      icon: 'default',
      border: '#D0D2D3',
      borderHover: '#B5B7B8',
      borderFocus: '#B5B7B8',
      borderActive: '#DADADA',
    },
    cta: {
      background: '#EB5424',
      backgroundHover: '#D94514',
      backgroundFocus: '#D94514',
      backgroundActive: '#BF3A11',
      text: '#FAFAFA',
      icon: 'white',
      border: '#EB5424',
      borderHover: '#D94514',
      borderFocus: '#D94514',
      borderActive: '#BF3A11',
    },
    destructive: {
      background: '#FF0000',
      backgroundHover: '#E40002',
      backgroundFocus: '#E40002',
      backgroundActive: '#BE0001',
      text: '#FAFAFA',
      icon: 'white',
      border: '#FF0000',
      borderHover: '#E40002',
      borderFocus: '#E40002',
      borderActive: '#BE0001',
    },
    success: {
      background: '#4CD964',
      backgroundHover: '#4CD964',
      backgroundFocus: '#4CD964',
      text: '#FAFAFA',
      icon: 'white',
      border: '#4CD964',
      borderHover: '#4CD964',
      borderFocus: '#4CD964',
      borderActive: '#4CD964',
      backgroundActive: undefined, // TODO: Review with Fer
    },
    link: {
      text: '#0a84ae',
      icon: 'blue',
      hover: '#0a84ae',
      focus: '#0a84ae',
    },
  },
  alert: {
    default: {
      background: '#F0F0F0',
      text: '#333',
    },
    information: {
      background: '#DBF4FC',
      text: '#097093',
    },
    success: {
      background: '#E5F8D1',
      text: '#3F6910',
    },
    warning: {
      background: '#FFF6CB',
      text: '#786600',
    },
    danger: {
      background: '#FFD8CC',
      text: '#801F00',
    },
  },
}

export default colors
